// login Types
export const SAMPLE_ACTION = 'SAMPLE_ACTION';
export const SAMPLE_ACTION_SUCCESS = 'SAMPLE_ACTION_SUCCESS';

// login Types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_ERROR_CLEARED = 'LOGIN_ERROR_CLEARED';

// signup action types
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';


// update   profile action types
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

// auth action types
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// entry action type
export const CREATE_ENTRY = 'CREATE_ENTRY';
export const CREATE_ENTRY_SUCCESS = 'CREATE_ENTRY_SUCCESS';
export const CREATE_ENTRY_FAILURE = 'CREATE_ENTRY_FAILURE';
export const CLEAR_PROGRESS = 'CLEAR_PROGRESS';

// list entry action type
export const GET_LIST_ENTRIES = 'GET_LIST_ENTRIES';
export const GET_LIST_ENTRIES_SUCCESS = 'GET_LIST_ENTRIES_SUCCESS';
export const GET_LIST_ENTRIES_FAILURE = 'GET_LIST_ENTRIES_FAILURE';

// get single entery
export const GET_SINGLE_ENTRY = 'GET_SINGLE_ENTRY';
export const GET_SINGLE_ENTRY_SUCCESS = 'GET_SINGLE_ENTRY_SUCCESS';
export const GET_SINGLE_ENTRY_FAILURE = 'GET_SINGLE_ENTRY_FAILURE';

// update diary entry action type
export const UPDATE_ENTRY = 'UPDATE_ENTRY';
export const UPDATE_ENTRY_SUCCESS = 'UPDATE_ENTRY_SUCCESS';
export const UPDATE_ENTRY_FAILURE = 'UPDATE_ENTRY_FAILURE';

// delete entry
export const DELETE_ENTRY = 'DELETE_ENTRY';
export const DELETE_ENTRY_SUCCESS = 'DELETE_ENTRY_SUCCESS';
export const DELETE_ENTRY_FAILURE = 'DELETE_ENTRY_FAILURE';

// profile action
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const GET_PROFILE_ENTRY = 'GET_PROFILE_ENTRY';
export const GET_PROFILE_ENTRY_SUCCESS = 'GET_PROFILE_ENTRY_SUCCESS';
export const GET_PROFILE_ENTRY_FAILURE = 'GET_PROFILE_ENTRY_FAILURE';
